# Generated by Django 2.2 on 2019-04-10 15:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название ордена')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='service.Orden', verbose_name='Орден')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='Текст вопроса')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='service.Test', verbose_name='Тест')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='planet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='service.Planet', verbose_name='Планета'),
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя джежая')),
                ('learning_planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jedis', to='service.Planet', verbose_name='Планета обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('email', models.CharField(max_length=25, verbose_name='Email')),
                ('padawan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='padawans', to='service.Jedi', verbose_name='Падаван')),
                ('residence_planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='service.Planet', verbose_name='Планета проживания')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='service.Candidate', verbose_name='Кандидат')),
            ],
        ),
    ]
